<?php 
		$title = "Lab 1: Basic XHTML Pages";
		$file = "lab1.php";
		$description = "Lab #1 is captured in this page, and demonstrates various special key combinations to produce currency, subscript,
		superscript, and code snippets, as well as two different styles of lists using XHTML. While the styling is very simple
		at this point, this lab focuses on getting familiar with HTML syntax that is the foundation of all websites.";
		$date = "February 17, 2020";
		$banner = "Lab #1: Basic XHTML Pages";	
		include '../header.php';
?>
	<div>
		<h3>Einstein's Relativity</h3>
		<p>For Einstein's Relativity formula you have to use the superscript (&lt;sup&gt;...&lt;/sup&gt;) and italic (&lt;i&gt;...&lt;/i&gt;) tags.
		It is wrapped in heading 2 (&lt;h2&gt;...&lt;/h2&gt;) tags to make it larger and bolder.<b> NOTE: be careful with proper nesting
		to ensure the page passes the XHTML validator. This line is bolded using the bold (&lt;b&gt;...&lt;/b&gt;) tags.</b></p>
		<h2><i>E = mc<sup>2</sup></i></h2>
	</div>
	<hr/>
	<div>
		<h3>Currency Conversion (use of special characters)</h3>
		<p>For many currencies worldwide, special characters are used. Some of these currencies include the British Pound (&pound;), the Euro (&euro;), and the Chinese Yen (&yen;).</p>
		<h2>$1.00CDN - $0.73USD = &pound;0.487 = &euro;0.651 = &yen;82.77</h2>
	</div>
	<hr/>
		<div>
			<h3>Code Snippet</h3>
			<p>For code snippets to be captured in HTML, it is neccessary to use special characters to represent code blocks in order to avoid parentheses and curly braces from being interpreted in the browser. 
			Below is an example of C++ code that can be captured in the browser without issue by using various special characters. Of particular importance when including blocks of code using HTML, is ensuring 
			that brackets are created using special character codes, such as &lt; for leading tags (&lt;) and &gt; for closing tags (&gt;).</p>		
			<code>
				#include &lt;iostream.h&gt;<br/>int main() <br/>{
				<br/>&nbsp;	cout &lt;&lt; "Hello, World!" &lt;&lt; endl;<br/>
				&nbsp;	return 0;<br/>}
			</code>
		</div>
		<hr/>
		<div>
			<h3>Chemistry Equation</h3>
			<p>The subscript special character code is useful for expressing chemistry equations. Chemistry equations often use the &lt;sub&gt;...&lt;/sub&gt; tags.</p>
			<h2><sub>2</sub> + O<sub>2</sub> => 2H<sub>2</sub>O + heat</h2>
		</div>
		<hr/>
		<div>
			<h3>List Example (order important)</h3>
			<p>To create an ordered list, in which the order is important and needs to be numbered in a specific way, the &lt;ol&gt;...&lt;/ol&gt; tags are used. Within them list items are declared using the &lt;li&gt;...&lt;/li&gt; tags for each item.</p>
			<h1>How to start a car</h1>
			<ol>
				<li>Place key in the ignition</li>
				<li>Depress the brake pedal</li>
				<li>Turn the ignition key</li>
			</ol>
		</div>
		<hr/>
		<div>
			<h3>List Example (order unimportant)</h3>
			<p>To create an ordered list, in which the order is unimportant, the &lt;ul&gt;...&lt;/ul&gt; tags are used, along with &lt;li&gt;...&lt;/li&gt; tags for each item. Another special character introduced in this unordered list is the ampersamp(&amp;), 
			which is generated by typing <i>&amp;amp;</i>.</p>
			<h1> Things to do before my trip</h1>
			<ul>
				<li>Re-new passwort</li>
				<li>Convert currency</li>
				<li>Print out reservations &amp; itineraries</li>
				<li>Verify vaccinations are up-to-date</li>
			</ul>
		</div>
		<hr class="bottom-rule" />
<?php include '../footer.php'; ?>